# Generated by Django 3.0.5 on 2020-04-26 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carname',
            options={'verbose_name': 'Car label', 'verbose_name_plural': 'Cars label'},
        ),
    ]
