# Generated by Django 3.0.5 on 2020-04-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200426_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='url',
        ),
    ]
