# Generated by Django 3.0.5 on 2020-04-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_remove_car_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='url',
        ),
    ]
