# Generated by Django 3.0.5 on 2020-04-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_remove_genre_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='указывать сумму в долларах', verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='genres',
            field=models.ManyToManyField(max_length=100, to='goods.Genre'),
        ),
    ]
