# Generated by Django 3.0.5 on 2020-04-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20200427_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='указывать сумму в долларах', verbose_name='Цена'),
        ),
    ]
