# Generated by Django 3.0.5 on 2020-04-28 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_rating_ratingstar_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='car',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='goods.Car', verbose_name='Car'),
        ),
    ]
