# Generated by Django 3.0.5 on 2020-04-28 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_auto_20200428_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Car', verbose_name='Car'),
        ),
    ]
