# Generated by Django 3.0.5 on 2020-05-16 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_auto_20200508_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Car', verbose_name='машина'),
        ),
    ]
