# Generated by Django 3.0.5 on 2020-05-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_auto_20200516_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(max_length=100, verbose_name='Тип топлива')),
            ],
            options={
                'verbose_name': 'Топливо',
                'verbose_name_plural': 'Топливо',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.ManyToManyField(max_length=100, to='goods.Specifications'),
        ),
    ]
