# Generated by Django 3.0.5 on 2020-05-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0015_auto_20200516_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='ip',
        ),
        migrations.AddField(
            model_name='rating',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254),
        ),
    ]
