# Generated by Django 3.0.5 on 2020-05-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_auto_20200530_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='poster',
            field=models.ImageField(default=0, upload_to='movies/', verbose_name='Фото'),
        ),
    ]
