# Generated by Django 3.0.5 on 2020-05-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0017_auto_20200530_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='poster',
            field=models.ImageField(default=None, upload_to='movies/', verbose_name='Фото'),
        ),
    ]
