# Generated by Django 3.0.5 on 2020-06-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0019_userinregistrated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinregistrated',
            name='password',
            field=models.IntegerField(verbose_name='Пароль'),
        ),
    ]
