# Generated by Django 3.0.5 on 2020-06-26 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0020_auto_20200619_1058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInRegistrated',
        ),
        migrations.AddField(
            model_name='car',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец машины'),
        ),
    ]
