# Generated by Django 3.0.5 on 2020-06-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0021_auto_20200626_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='poster',
            field=models.ImageField(default=None, null=True, upload_to='movies/', verbose_name='Фото'),
        ),
    ]
