# Generated by Django 3.0.5 on 2020-07-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0022_auto_20200630_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carshorts',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='movie_shots/', verbose_name='Pictures'),
        ),
    ]
