# Generated by Django 3.0.5 on 2020-07-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0023_auto_20200721_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='poster',
            field=models.ImageField(default=None, null=True, upload_to='media/movies/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='carshorts',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='media/movie_shots/', verbose_name='Pictures'),
        ),
    ]
