# Generated by Django 3.0.5 on 2020-07-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0024_auto_20200726_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='poster',
            field=models.ImageField(default=None, null=True, upload_to='movies/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='carshorts',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='movie_shots/', verbose_name='Pictures'),
        ),
    ]
